---
# Flux System Kustomization - Manages Flux itself
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux-system
    app.kubernetes.io/part-of: flux
spec:
  interval: 10m
  path: "./clusters/dev/us-west-2/flux-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  serviceAccountName: flux-system
  timeout: 5m
  retryInterval: 2m
  postBuild:
    substitute:
      CLUSTER_NAME: "dev-us-west-2"
      ENVIRONMENT: "dev"
      REGION: "us-west-2"
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: source-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: notification-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: helm-controller
      namespace: flux-system
