---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

namePrefix: dev-

replicas:
  - name: myapp
    count: 1

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
      spec:
        template:
          spec:
            containers:
            - name: myapp
              env:
              - name: ENVIRONMENT
                value: "dev"
    target:
      kind: Deployment
      name: myapp

commonLabels:
  environment: dev

