---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo-prod
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/jnssa/GitOps
  ref:
    branch: prod
  # No secretRef needed for public repos

