---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-staging
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: gitops-repo-staging
  path: ./apps/myapp/kustomize/overlays/staging
  prune: true
  targetNamespace: staging
  wait: true
  timeout: 3m
  dependsOn:
    - name: myapp-dev

