apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-apps
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  path: ./exercise-01-git-source/apps
  prune: true
  wait: true
  timeout: 3m

