apiVersion: v1
kind: Service
metadata:
  name: team-b-service
  namespace: team-b
  labels:
    app: team-b-app
    tenant: team-b
spec:
  type: ClusterIP
  selector:
    app: team-b-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

