---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-reconciler
  namespace: team-a
  labels:
    tenant: team-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-reconciler
  namespace: team-a
  labels:
    tenant: team-a
rules:
  # Allow managing all standard workload resources
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - persistentvolumeclaims
      - pods
      - pods/log
      - events
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
  # Allow Flux to manage its own resources within the namespace
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups: ["notification.toolkit.fluxcd.io"]
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources:
      - "*"
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-reconciler
  namespace: team-a
  labels:
    tenant: team-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-reconciler
subjects:
  - kind: ServiceAccount
    name: flux-reconciler
    namespace: team-a

