---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-consumer
  namespace: team-a
  labels:
    app: secret-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-consumer
  template:
    metadata:
      labels:
        app: secret-consumer
    spec:
      containers:
      - name: app
        image: busybox:1.36
        command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Secret Consumer App Started"
          echo "===================="
          echo "Reading secret from environment variable:"
          echo "MY_MESSAGE: $MY_MESSAGE"
          echo "===================="
          echo "App will sleep indefinitely. Use 'kubectl logs' to see the output."
          while true; do
            echo "$(date): Secret value is: $MY_MESSAGE"
            sleep 300
          done
        env:
        - name: MY_MESSAGE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MY_MESSAGE
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi

