---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: team-a
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
# Vault token secret - In production, use more secure methods like Kubernetes auth
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: team-a
type: Opaque
stringData:
  token: "root"  # This is the dev token - DO NOT use in production!

