apiVersion: v1
kind: Service
metadata:
  name: team-a-service
  namespace: team-a
  labels:
    app: team-a-app
    tenant: team-a
spec:
  type: ClusterIP
  selector:
    app: team-a-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

