apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - name: myapp
        image: nginx:1.27-alpine
        env:
        - name: APP_MODE
          value: "dev"

