---
# Base kustomization for myapp
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapp-base
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/part-of: myapp

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: myapp
  app.kubernetes.io/part-of: myapp
  app.kubernetes.io/managed-by: flux

images:
  - name: myapp
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: myapp
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "dev"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "us-west-2"

configMapGenerator:
  - name: myapp-config
    literals:
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
      - TRACING_ENABLED=false

secretGenerator:
  - name: myapp-secrets
    literals:
      - DATABASE_URL=postgresql://user:pass@localhost:5432/myapp
      - API_KEY=default-api-key
    type: Opaque
