---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-redis
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/helm-releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m

