---
apiVersion: v1
kind: Service
metadata:
  name: versioned-app
  labels:
    app: versioned-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: versioned-app

