---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: versioned-app-fixed
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: versioned-app-fixed
  path: ./apps/versioned-app/base
  prune: true
  targetNamespace: version-fixed
  wait: true
  timeout: 3m



