apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml
- hpa-patch.yaml

commonLabels:
  environment: production

