apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: myapp
        image: ghcr.io/ORG/REPO/myapp:staging
        env:
        - name: APP_MODE
          value: "staging"

