---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-prod
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: gitops-repo-prod
  path: ./apps/myapp/kustomize/overlays/prod
  prune: true
  targetNamespace: prod
  wait: true
  timeout: 3m
  dependsOn:
    - name: myapp-staging

