---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-dev
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: gitops-repo-dev
  path: ./apps/myapp/kustomize/overlays/dev
  prune: true
  targetNamespace: dev
  wait: true
  timeout: 3m

