---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: backend-repo
  namespace: flux-system
spec:
  interval: 3m0s
  ref:
    branch: main
  url: file:///home/jnssa/GitOps/flux-bootstrap-demo
  ignore: |
    # exclude all
    /*
    # include apps/backend
    !/apps/backend/

