---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: frontend-repo
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: main
  url: file:///home/jnssa/GitOps/flux-bootstrap-demo
  ignore: |
    # exclude all
    /*
    # include apps/frontend
    !/apps/frontend/

