---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

namePrefix: staging-

replicas:
  - name: myapp
    count: 2

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
      spec:
        template:
          spec:
            containers:
            - name: myapp
              env:
              - name: ENVIRONMENT
                value: "staging"
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "50m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
    target:
      kind: Deployment
      name: myapp

commonLabels:
  environment: staging

