---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

namePrefix: prod-

replicas:
  - name: myapp
    count: 3

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
      spec:
        template:
          spec:
            containers:
            - name: myapp
              env:
              - name: ENVIRONMENT
                value: "prod"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "1000m"
    target:
      kind: Deployment
      name: myapp

commonLabels:
  environment: prod

