---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: infrastructure-redis
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: backend
    namespace: apps
  timeout: 2m

