---
# Secrets Management Configuration
# SOPS Configuration for encrypted secrets

apiVersion: v1
kind: ConfigMap
metadata:
  name: sops-config
  namespace: flux-system
  labels:
    app.kubernetes.io/name: sops-config
    app.kubernetes.io/part-of: flux
data:
  # SOPS configuration
  sops-config.yaml: |
    keys:
      - &age_key age1qyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqs
    creation_rules:
      - path_regex: \.yaml$
        age: *age_key
        encrypted_regex: '^(data|stringData)$'

---
# External Secrets Operator configuration
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: aws-secrets-manager
    app.kubernetes.io/part-of: flux
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
# External Secret for myapp
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-secrets
  namespace: myapp-prod
  labels:
    app.kubernetes.io/name: myapp-secrets
    app.kubernetes.io/part-of: flux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: myapp-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: myapp/prod/database-url
    - secretKey: api-key
      remoteRef:
        key: myapp/prod/api-key
    - secretKey: jwt-secret
      remoteRef:
        key: myapp/prod/jwt-secret

---
# Sealed Secrets configuration
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-key
  namespace: sealed-secrets
  labels:
    app.kubernetes.io/name: sealed-secrets-key
    app.kubernetes.io/part-of: flux
type: kubernetes.io/tls
data:
  # This would contain the actual sealed secrets public key
  tls.crt: LS0tLS1CRUdJTi...
  tls.key: LS0tLS1CRUdJTi...

---
# Network Policy for secrets namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secrets-network-policy
  namespace: flux-system
  labels:
    app.kubernetes.io/name: secrets-network-policy
    app.kubernetes.io/part-of: flux
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: flux-system
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: flux-system
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
