---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: test
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: podinfo
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 9898
  analysis:
    interval: 1m
    threshold: 5
    iterations: 10
    # A/B testing match conditions
    match:
      # Match requests with X-Canary header set to "insider"
      - headers:
          x-canary:
            exact: "insider"
      # Match requests with cookie containing canary=always
      - headers:
          cookie:
            regex: "^(.*?;)?(canary=always)(;.*)?$"
