---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: test
spec:
  # Provider must be nginx for A/B testing with NGINX Ingress
  provider: nginx
  # Deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  # The maximum time in seconds for the canary deployment
  # to make progress before it is rolled back (default 600s)
  progressDeadlineSeconds: 60
  # Reference to the ingress for A/B testing
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: podinfo
  service:
    # Service port number
    port: 80
    # Container port number or name
    targetPort: 9898
  analysis:
    # Schedule interval (default 60s)
    interval: 1m
    # Max number of failed metric checks before rollback
    threshold: 10
    # Maximum number of iterations
    maxWeight: 50
    # stepWeight for progressive traffic increase
    stepWeight: 10
    # Webhooks section can be added if flagger-loadtester is installed
    # webhooks:
    #   - name: acceptance-test
    #     type: pre-rollout
    #     url: http://flagger-loadtester.test/
    #     timeout: 30s
    #     metadata:
    #       type: bash
    #       cmd: "curl -sd 'test' http://podinfo-canary.test/token | grep token"
    #   - name: load-test
    #     type: rollout
    #     url: http://flagger-loadtester.test/
    #     metadata:
    #       cmd: "hey -z 2m -q 10 -c 2 -H 'X-Canary: insider' -host app.example.com http://ingress-nginx-controller.ingress-nginx/"

